server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://manish:fBxLDjziEgA6CCEn@vrv.tzoxj.mongodb.net/?retryWrites=true&w=majority&appName=vrv
      database: rbac

logging:
  level:
    root: WARN

secret:
  key: CHEFsEVfypW#7g9^k*Z8$VTaK+HaV^uv
